routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('tes', 'HomeController@tes');

Auth::routes();

Route::get('/register', function(){
   return "Disable"; 
});
Route::get('/logout', 'Auth\LoginController@logout')->name('logout')->middleware(['auth']);



Route::group(['middleware' => 'auth'], function(){

    Route::get('/home', 'HomeController@index')->name('index')->middleware(['level:pegawai|konsumen|supplier']);

    Route::resource('pegawai', 'PegawaiController')->middleware(['level:pegawai','jabatan:admin']);
    Route::resource('konsumen', 'KonsumenController')->middleware(['level:pegawai','jabatan:admin|manager']);
    Route::resource('produk', 'ProdukController')->middleware(['level:pegawai','jabatan:admin|manager|produksi|gudang']);
    Route::resource('supplier', 'SupplierController')->middleware(['level:pegawai','jabatan:admin|manager|purchasing']);
    Route::resource('kendaraan', 'KendaraanController')->middleware(['level:pegawai','jabatan:admin|manager|distribusi']);
    Route::get('kendaraan/switch/{id}', 'KendaraanController@switchStatus')->name('kendaraan.switch');

    Route::resource('bahan-baku-supplier', 'BahanBakuSupplierController')->middleware(['level:pegawai|supplier','jabatan:admin|manager|gudang|purchasing']);

    Route::group(['prefix' => 'bahan-baku/penerimaan', 'middleware' => ['level:pegawai','jabatan:admin|manager|gudang']], function() {
        Route::get('/', 'BahanBakuController@penerimaan')->name('penerimaan.index');
        Route::get('/terima/{id}', 'BahanBakuController@terima')->name('penerimaan.terima');
    });
    Route::resource('bahan-baku', 'BahanBakuController')->middleware(['level:pegawai','jabatan:admin|manager|gudang|supplier|distribusi|purchasing']);

    Route::get('/bom/get-ajax', 'BOMController@getAjax')->name('bom.ajax');
    Route::resource('bom', 'BOMController')->middleware(['level:pegawai','jabatan:admin|manager|produksi']);

    Route::group(['prefix' => 'pesanan', 'middleware' => ['level:pegawai|konsumen', 'jabatan:admin|manager|produksi']], function() {
        Route::get('/proses/{id}', 'PesananController@proses')->name('pesanan.proses');
    	Route::get('/tolak/{id}', 'PesananController@tolak')->name('pesanan.tolak');
    	Route::get('/selesai/{id}', 'PesananController@selesai')->name('pesanan.selesai');
    	Route::get('/detail/{id}', 'PesananController@detail')->name('pesanan.detail');

        Route::get('/index', 'PesananController@index')->name('pesanan.index');

        Route::get('/design-baru', 'PesananDesignBaruController@index')->name('pesanan.design.baru.index');
        Route::get('/design-baru/create', 'PesananDesignBaruController@create')->name('pesanan.design.baru.create');
        Route::post('/design-baru/store', 'PesananDesignBaruController@store')->name('pesanan.design.baru.store');
        Route::get('/design-baru/proses/{id}', 'PesananDesignBaruController@proses')->name('pesanan.design.baru.proses');
        Route::get('/design-baru/tolak/{id}', 'PesananDesignBaruController@tolak')->name('pesanan.design.baru.tolak');
        Route::post('/design-baru/buat/{id}', 'PesananDesignBaruController@buatPesanan')->name('pesanan.design.baru.buat');

        Route::get('/{bb}/produk', 'PesananController@produk')->name('pesanan.produk');

        Route::get('/bb-perusahaan/create/{kode}', 'PesananController@BBPerusahaanCreate')->name('pesanan.bb.perusahaan.create');
        Route::post('/bb-perusahaan/store', 'PesananController@BBPerusahaanStore')->name('pesanan.bb.perusahaan.store');

        Route::get('/bb-konsumen/create/{kode}', 'PesananController@BBKonsumenCreate')->name('pesanan.bb.konsumen.create');
        Route::post('/bb-konsumen/store', 'PesananController@BBKonsumenStore')->name('pesanan.bb.konsumen.store');

        Route::get('/cetak/{id}', 'PesananController@cetak')->name('pesanan.cetak');
    });

    Route::group(['prefix' => 'pengadaan', 'middleware' => ['level:pegawai', 'jabatan:admin|manager|gudang|purchasing']], function() {
        Route::get('/', 'PengadaanController@index')->name('pengadaan.index');
        Route::get('/pesanan', 'PengadaanController@indexPesanan')->name('pengadaan.index-pesanan');
        Route::get('/detail/{id}', 'PengadaanController@detail')->name('pengadaan.detail');
        Route::get('/setujui/{id}', 'PengadaanController@setujui')->name('pengadaan.setujui');
        Route::get('/tolak/{id}', 'PengadaanController@tolak')->name('pengadaan.tolak');
        Route::get('/create/', 'PengadaanController@create')->name('pengadaan.create');
        Route::post('/store/', 'PengadaanController@store')->name('pengadaan.store');
    });

    Route::get('/profile', 'ProfileController@form')->name('profile');
    Route::put('/profile', 'ProfileController@update');


    Route::group(['prefix' => 'penjualan', 'middleware' => ['level:supplier']], function() {
        Route::get('/', 'PenjualanBahanBakuController@index')->name('supplier.penjualan.index');
        Route::get('/pengiriman', 'PenjualanBahanBakuController@pengiriman')->name('supplier.pengiriman');
        Route::get('/{id}', 'PenjualanBahanBakuController@kirim')->name('supplier.penjualan.kirim');
    });

    Route::group(['prefix' => 'produksi', 'middleware' => ['level:pegawai|konsumen', 'jabatan:admin|produksi|gudang']], function() {
        Route::get('/', 'ProduksiController@index')->name('produksi.index');
        Route::get('/pesanan/{id}', 'ProduksiController@indexPesanan')->name('produksi.index-pesanan');
        Route::get('/detail/{id}', 'ProduksiController@detail')->name('produksi.detail');
        Route::get('/setujui/{id}', 'ProduksiController@setujui')->name('produksi.setujui');
        Route::get('/selesai/{id}', 'ProduksiController@selesai')->name('produksi.selesai');
        Route::get('/create/{id}', 'ProduksiController@create')->name('produksi.create');
        Route::post('/store/{id}', 'ProduksiController@store')->name('produksi.store');
    });

    Route::group(['prefix' => 'pengiriman'], function () {
        Route::get('/', 'PengirimanController@index')->name('pengiriman.index');
        Route::get('/pesanan/{id}', 'PengirimanController@indexPesanan')->name('pengiriman.pesanan');
        Route::get('/create/{id}', 'PengirimanController@create')->name('pengiriman.create');
        Route::post('/store/{id}', 'PengirimanController@store')->name('pengiriman.store');
        Route::get('/proses/{id}', 'PengirimanController@proses')->name('pengiriman.proses');
        Route::post('/update/{id}', 'PengirimanController@update')->name('pengiriman.update');
        Route::get('/terima/{id}', 'PengirimanController@terima')->name('pengiriman.terima');
        Route::get('/request/{id}', 'PengirimanController@requestPengiriman')->name('pengiriman.request');
        Route::get('/cetak/{id}', 'PengirimanController@cetakSJ')->name('pengiriman.cetaksj');
    });

    Route::group(['prefix' => 'laporan'], function () {
        Route::get('/pesanan', 'LaporanController@pesanan')->name('laporan.pesanan');
        Route::post('/pesanan/cetak', 'LaporanController@pesananCetak')->name('laporan.pesanan.cetak');
        Route::get('/pengiriman', 'LaporanController@pengiriman')->name('laporan.pengiriman');
        Route::post('/pengiriman/cetak', 'LaporanController@pengirimanCetak')->name('laporan.pengiriman.cetak');
        Route::get('/pengadaan', 'LaporanController@pengadaan')->name('laporan.pengadaan');
        Route::post('/pengadaan/cetak', 'LaporanController@pengadaanCetak')->name('laporan.pengadaan.cetak');
    });


    Route::get('/', function() {
        return redirect()->route('index');
    });


});

app/Kendaraan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kendaraan extends Model
{   
	protected $table = 'kendaraan';

	public $timestamps = false;
}

app/Http/Controllers/KendaraanController.php
<?php

namespace App\Http\Controllers;

use App\Kendaraan;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Exception, DB;

class KendaraanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $param = $request->filter;
        $kendaraans = Kendaraan::where('nopol', 'like', '%' . ($request->filter['nopol'] ?? '')  . '%')
                ->where('kapasitas', 'like', ($request->filter['kontak'] ?? '%') )
                ->where('supir', 'like', ('%'.$request->filter['supir'].'%' ?? '%') )
                ->paginate(10);

        return view('kendaraan.index', compact('kendaraans', 'param'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('kendaraan.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nopol' => 'string|min:5|max:11|unique:kendaraan,nopol',
            'kapasitas' => 'numeric|digits_between:1,5',
            'name' => 'required|max:50|alpha',
        ]);

        $kendaraan = new Kendaraan;
        $kendaraan->nopol = $request->nopol;
        $kendaraan->kapasitas = $request->kapasitas;
        $kendaraan->supir = $request->name;
        $kendaraan->save();

        return redirect()->route('kendaraan.index')->with('alert-success', 'Berhasil menambah kendaraan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Kendaraan  $kendaraan
     * @return \Illuminate\Http\Response
     */
    public function show(Kendaraan $kendaraan)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Kendaraan  $kendaraan
     * @return \Illuminate\Http\Response
     */
    public function edit(Kendaraan $kendaraan)
    {
        return view('kendaraan.edit', compact('kendaraan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Kendaraan  $kendaraan
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Kendaraan $kendaraan)
    {
        $this->validate($request, [
            'nopol' => [
                'string',
                'min:5',
                'max:11',
                Rule::unique('kendaraan')->ignore($kendaraan->id),
            ],
            'kapasitas' => 'numeric|digits_between:1,5',
            'name' => 'required|max:50|alpha',
        ]);

        $kendaraan->nopol = $request->nopol;
        $kendaraan->kapasitas = $request->kapasitas;
        $kendaraan->supir = $request->name;
        $kendaraan->save();

        return redirect()->route('kendaraan.index')->with('alert-success', 'Berhasil mengubah kendaraan!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Kendaraan  $kendaraan
     * @return \Illuminate\Http\Response
     */
    public function destroy(Kendaraan $kendaraan)
    {
        DB::beginTransaction();
        try {

            $kendaraan->delete();

            DB::commit();

        } catch (Exception $e) {

            DB::rollBack();
            return redirect()->back()->withInput()->with('alert-error', $e->getMessage());

        }

        return redirect()->route('kendaraan.index')->with('alert-success', 'Berhasil menghapus kendaraan!');
    }

    public function switchStatus($id) {
        $kendaraan = Kendaraan::findOrFail($id);

        if($kendaraan->status == 1){
            $kendaraan->status = 0;
        }else{
            $kendaraan->status = 1;
        }
        $kendaraan->save();

        return redirect()->back()->with('alert-success', 'Berhasil mengubah status kendaraan');
    }
}

resources/views/kendaraan/create.blade.php
@extends('layouts.app')

@section('css')
<link rel="stylesheet" type="text/css" href="{{ asset('guru/default/assets/pages/j-pro/css/demo.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('guru/default/assets/pages/j-pro/css/font-awesome.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('guru/default/assets/pages/j-pro/css/j-pro-modern.css') }}">
@endsection

@section('content')
<div class="page-header card">
    <div class="row align-items-end">
        <div class="col-lg-8">
            <div class="page-header-title">
                <i class="icofont icofont-box bg-c-green"></i>
                <div class="d-inline">
                    <h4>Tambah Data Kendaraan</h4>
                    <span></span>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="page-header-breadcrumb">
                <ul class="breadcrumb-title">
                    <li class="breadcrumb-item">
                        <a href="{{ route('index') }}">
                            <i class="icofont icofont-home"></i>
                        </a>
                    </li>
                    <li class="breadcrumb-item"><a href="{{ route('kendaraan.index') }}">Kendaraan</a>
                    </li>
                    <li class="breadcrumb-item"><a href="#">Tambah Kendaraan</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="page-body">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-block">
                    <div class="j-wrapper j-wrapper-640">
                        <form action="{{ route('kendaraan.store') }}" method="post" class="j-pro" id="j-pro" novalidate="" enctype="multipart/form-data">
                            @csrf
                            <div class="j-content">

                                <!-- start email phone -->
                                <div class="j-row">
                                    <div class="j-span6 j-unit">
                                        <label class="j-label">No Pol</label>
                                        <div class="j-input {{ $errors->has('nopol') ? ' j-error-view' : '' }}">
                                            <label class="j-icon-right" for="nopol">
                                                <i class="icofont icofont-barcode"></i>
                                            </label>
                                            <input type="text" id="nopol" name="nopol" value="{{ old('nopol') }}">
                                        @if ( $errors->has('nopol') )
                                            <span class="j-error-view">{{$errors->first('nopol')}}</span>
                                        @endif
                                        </div>
                                    </div>
                                    <div class="j-span6 j-unit">
                                        <label class="j-label">Kapasitas (PCS)</label>
                                        <div class="j-input {{ $errors->has('kapasitas') ? ' j-error-view' : '' }}">
                                            <label class="j-icon-right" for="kapasitas">
                                                <i class="icofont icofont-box"></i>
                                            </label>
                                            <input type="text" id="kapasitas" name="kapasitas" value="{{ old('kapasitas') }}">
                                        @if ( $errors->has('kapasitas') )
                                            <span class="j-error-view">{{$errors->first('kapasitas')}}</span>
                                        @endif
                                        </div>
                                    </div>
                                </div>
                                <!-- start name -->
                                <div class="j-unit">
                                    <label class="j-label">Nama Supir</label>
                                    <div class="j-input {{ $errors->has('name') ? ' j-error-view' : '' }}">
                                        <label class="j-icon-right" for="name">
                                            <i class="icofont icofont-ui-user"></i>
                                        </label>
                                        <input type="text" id="name" name="name" value="{{ old('name') }}">
                                        @if ( $errors->has('name') )
                                            <span class="j-error-view">{{$errors->first('name')}}</span>
                                        @endif
                                    </div>
                                </div>
                                <!-- end name -->
                                <!-- start response from server -->
                                <div class="j-response"></div>
                                <!-- end response from server -->
                            </div>
                            <!-- end /.content -->
                            <div class="j-footer">
                                <button type="submit" class="btn btn-primary">Simpan</button>
                            </div>
                            <!-- end /.footer -->
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<form action="" method="POST" id="deleteForm">
    @csrf
    @method('DELETE')
    <input type="submit" style="display: none;">
</form>
@endsection

@section('js')
<script type="text/javascript">
$('button#delete').on('click', function(){
    var href = $(this).attr('href');
    var title = $(this).data('title');
    swal({
      title: "Anda yakin akan menghapus kendaraan bernama "+ title +" ?",
      text: "Setelah dihapus data tidak dapat dikembalikan !",
      icon: "warning",
      buttons: true,
      dangerMode: true,
    })
    .then((willDelete) => {
      if (willDelete) {
        $('#deleteForm').attr('action', href);
        $('#deleteForm').submit();
      }
    });
});
</script>
@endsection

resources/views/kendaraan/edit.blade.php
@extends('layouts.app')

@section('css')
<link rel="stylesheet" type="text/css" href="{{ asset('guru/default/assets/pages/j-pro/css/demo.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('guru/default/assets/pages/j-pro/css/font-awesome.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('guru/default/assets/pages/j-pro/css/j-pro-modern.css') }}">
@endsection

@section('content')
<div class="page-header card">
    <div class="row align-items-end">
        <div class="col-lg-8">
            <div class="page-header-title">
                <i class="icofont icofont-box bg-c-green"></i>
                <div class="d-inline">
                    <h4>Edit Data Kendaraan</h4>
                    <span></span>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="page-header-breadcrumb">
                <ul class="breadcrumb-title">
                    <li class="breadcrumb-item">
                        <a href="{{ route('index') }}">
                            <i class="icofont icofont-home"></i>
                        </a>
                    </li>
                    <li class="breadcrumb-item"><a href="{{ route('kendaraan.index') }}">Kendaraan</a>
                    </li>
                    <li class="breadcrumb-item"><a href="#">Edit Kendaraan</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="page-body">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-block">
                    <div class="j-wrapper j-wrapper-640">
                        <form action="{{ route('kendaraan.update', $kendaraan) }}" method="post" class="j-pro" id="j-pro" novalidate="" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="j-content">

                                <!-- start email phone -->
                                <div class="j-row">
                                    <div class="j-span6 j-unit">
                                        <label class="j-label">No Pol</label>
                                        <div class="j-input {{ $errors->has('nopol') ? ' j-error-view' : '' }}">
                                            <label class="j-icon-right" for="nopol">
                                                <i class="icofont icofont-barcode"></i>
                                            </label>
                                            <input type="text" id="nopol" name="nopol" value="{{ old('nopol') ?? $kendaraan->nopol }}">
                                        @if ( $errors->has('nopol') )
                                            <span class="j-error-view">{{$errors->first('nopol')}}</span>
                                        @endif
                                        </div>
                                    </div>
                                    <div class="j-span6 j-unit">
                                        <label class="j-label">Kapasitas (PCS)</label>
                                        <div class="j-input {{ $errors->has('kapasitas') ? ' j-error-view' : '' }}"">
                                            <label class="j-icon-right" for="kapasitas">
                                                <i class="icofont icofont-box"></i>
                                            </label>
                                            <input type="text" id="kapasitas" name="kapasitas" value="{{ old('kapasitas') ?? $kendaraan->kapasitas }}">
                                        @if ( $errors->has('kapasitas') )
                                            <span class="j-error-view">{{$errors->first('kapasitas')}}</span>
                                        @endif
                                        </div>
                                    </div>
                                </div>
                                <!-- start name -->
                                <div class="j-unit">
                                    <label class="j-label">Nama Supir</label>
                                    <div class="j-input {{ $errors->has('name') ? ' j-error-view' : '' }}">
                                        <label class="j-icon-right" for="name">
                                            <i class="icofont icofont-ui-user"></i>
                                        </label>
                                        <input type="text" id="name" name="name" value="{{ old('name') ?? $kendaraan->supir }}">
                                        @if ( $errors->has('name') )
                                            <span class="j-error-view">{{$errors->first('name')}}</span>
                                        @endif
                                    </div>
                                </div>
                                <!-- end name -->
                                <!-- start response from server -->
                                <div class="j-response"></div>
                                <!-- end response from server -->
                            </div>
                            <!-- end /.content -->
                            <div class="j-footer">
                                <button type="submit" class="btn btn-primary">Simpan</button>
                            </div>
                            <!-- end /.footer -->
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<form action="" method="POST" id="deleteForm">
    @csrf
    @method('DELETE')
    <input type="submit" style="display: none;">
</form>
@endsection

@section('js')
<script type="text/javascript">
$('button#delete').on('click', function(){
    var href = $(this).attr('href');
    var title = $(this).data('title');
    swal({
      title: "Anda yakin akan menghapus kendaraan bernama "+ title +" ?",
      text: "Setelah dihapus data tidak dapat dikembalikan !",
      icon: "warning",
      buttons: true,
      dangerMode: true,
    })
    .then((willDelete) => {
      if (willDelete) {
        $('#deleteForm').attr('action', href);
        $('#deleteForm').submit();
      }
    });
});
</script>
@endsection

resources/views/kendaraan/index.blade.php
@extends('layouts.app')

@section('content')
<div class="page-header card">
    <div class="row align-items-end">
        <div class="col-lg-8">
            <div class="page-header-title">
                <i class="icofont icofont-box bg-c-green"></i>
                <div class="d-inline">
                    <h4>Kelola Data Kendaraan</h4>
                    <span>Tambah Data Kendaraan, Ubah Data Kendaraan dan Hapus Data Kendaraan</span>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="page-header-breadcrumb">
                <ul class="breadcrumb-title">
                    <li class="breadcrumb-item">
                        <a href="{{ route('index') }}">
                            <i class="icofont icofont-home"></i>
                        </a>
                    </li>
                    <li class="breadcrumb-item"><a href="{{ route('kendaraan.index') }}">Kendaraan</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="page-body">
    <div class="card">
        <div class="card-header">
            <a href="{{ route('kendaraan.create') }}"><button class="btn btn-sm btn-primary">Tambah Kendaraan</button></a>
        </div>
        <div class="card-block table-border-style">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>No Pol</th>
                            <th>Kapasitas (PCS)</th>
                            <th>Supir</th>
                            <th>Status</th>
                            <th>#</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr style="background:#e9ecef">
                            <form action="" method="GET" name="search_form" id="search_form">
                            <td>
                                <input type="text" class="form-control form-control-sm" name="filter[nopol]" value="{{ $param['nopol'] ?? '' }}">
                            </td>
                            <td>
                                <input type="text" class="form-control form-control-sm" name="filter[kapasitas]" value="{{ $param['kapasitas'] ?? ''}}">
                            </td>
                            <td>
                                <input type="text" class="form-control form-control-sm" name="filter[supir]" value="{{ $param['supir'] ?? ''}}">
                            </td>
                            <td></td>
                            <td>
                                <button type="submit" class="btn btn-info btn-bordered btn-sm">Cari
                                </button>
                                <button type="reset" onclick="javascript:window.location.assign('{{ route('kendaraan.index') }}');" class="btn btn-info btn-bordered btn-sm">
                                    Reset
                                </button>
                            </td>
                            </form>
                        </tr>
                    @foreach ($kendaraans as $kendaraan)
                        <tr>
                            <td>{{ $kendaraan->nopol }}</td>
                            <td>{{ $kendaraan->kapasitas }}</td>
                            <td>{{ $kendaraan->supir }}</td>
                            <td>{{ $kendaraan->status == 0 ? 'Tidak Tersedia' : 'Tersedia' }}</td>
                            <td>
                              <a href="{{ route('kendaraan.edit', $kendaraan) }}">
                                  <button class="btn btn-mini btn-warning">Edit</button>
                              </a>
                              <a href="{{ route('kendaraan.switch', $kendaraan) }}">
                                  <button class="btn btn-mini btn-primary">Ubah Status</button>
                              </a>
                                <button id="delete" data-title="{{$kendaraan->nama}}" href="{{ route('kendaraan.destroy', $kendaraan) }}" class="btn btn-mini btn-danger">Hapus</button>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <div style="padding: 15px;width: 100%">
                    <center>{{ $kendaraans->appends(request()->except('page'))->links() }}</center>
                </div>
            </div>
        </div>
    </div>
</div>

<form action="" method="POST" id="deleteForm">
    @csrf
    @method('DELETE')
    <input type="submit" style="display: none;">
</form>
@endsection

@section('js')
<script type="text/javascript">
$('button#delete').on('click', function(){
    var href = $(this).attr('href');
    var title = $(this).data('title');
    swal({
      title: "Anda yakin akan menghapus kendaraan bernama "+ title +" ?",
      text: "Setelah dihapus data tidak dapat dikembalikan !",
      icon: "warning",
      buttons: true,
      dangerMode: true,
    })
    .then((willDelete) => {
      if (willDelete) {
        $('#deleteForm').attr('action', href);
        $('#deleteForm').submit();
      }
    });
});
</script>
@endsection