routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('tes', 'HomeController@tes');

Auth::routes();

Route::get('/register', function(){
   return "Disable"; 
});
Route::get('/logout', 'Auth\LoginController@logout')->name('logout')->middleware(['auth']);



Route::group(['middleware' => 'auth'], function(){

    Route::get('/home', 'HomeController@index')->name('index')->middleware(['level:pegawai|konsumen|supplier']);

    Route::resource('pegawai', 'PegawaiController')->middleware(['level:pegawai','jabatan:admin']);
    Route::resource('konsumen', 'KonsumenController')->middleware(['level:pegawai','jabatan:admin|manager']);
    Route::resource('produk', 'ProdukController')->middleware(['level:pegawai','jabatan:admin|manager|produksi|gudang']);
    Route::resource('supplier', 'SupplierController')->middleware(['level:pegawai','jabatan:admin|manager|purchasing']);
    Route::resource('kendaraan', 'KendaraanController')->middleware(['level:pegawai','jabatan:admin|manager|distribusi']);
    Route::get('kendaraan/switch/{id}', 'KendaraanController@switchStatus')->name('kendaraan.switch');

    Route::resource('bahan-baku-supplier', 'BahanBakuSupplierController')->middleware(['level:pegawai|supplier','jabatan:admin|manager|gudang|purchasing']);

    Route::group(['prefix' => 'bahan-baku/penerimaan', 'middleware' => ['level:pegawai','jabatan:admin|manager|gudang']], function() {
        Route::get('/', 'BahanBakuController@penerimaan')->name('penerimaan.index');
        Route::get('/terima/{id}', 'BahanBakuController@terima')->name('penerimaan.terima');
    });
    Route::resource('bahan-baku', 'BahanBakuController')->middleware(['level:pegawai','jabatan:admin|manager|gudang|supplier|distribusi|purchasing']);

    Route::get('/bom/get-ajax', 'BOMController@getAjax')->name('bom.ajax');
    Route::resource('bom', 'BOMController')->middleware(['level:pegawai','jabatan:admin|manager|produksi']);

    Route::group(['prefix' => 'pesanan', 'middleware' => ['level:pegawai|konsumen', 'jabatan:admin|manager|produksi']], function() {
        Route::get('/proses/{id}', 'PesananController@proses')->name('pesanan.proses');
    	Route::get('/tolak/{id}', 'PesananController@tolak')->name('pesanan.tolak');
    	Route::get('/selesai/{id}', 'PesananController@selesai')->name('pesanan.selesai');
    	Route::get('/detail/{id}', 'PesananController@detail')->name('pesanan.detail');

        Route::get('/index', 'PesananController@index')->name('pesanan.index');

        Route::get('/design-baru', 'PesananDesignBaruController@index')->name('pesanan.design.baru.index');
        Route::get('/design-baru/create', 'PesananDesignBaruController@create')->name('pesanan.design.baru.create');
        Route::post('/design-baru/store', 'PesananDesignBaruController@store')->name('pesanan.design.baru.store');
        Route::get('/design-baru/proses/{id}', 'PesananDesignBaruController@proses')->name('pesanan.design.baru.proses');
        Route::get('/design-baru/tolak/{id}', 'PesananDesignBaruController@tolak')->name('pesanan.design.baru.tolak');
        Route::post('/design-baru/buat/{id}', 'PesananDesignBaruController@buatPesanan')->name('pesanan.design.baru.buat');

        Route::get('/{bb}/produk', 'PesananController@produk')->name('pesanan.produk');

        Route::get('/bb-perusahaan/create/{kode}', 'PesananController@BBPerusahaanCreate')->name('pesanan.bb.perusahaan.create');
        Route::post('/bb-perusahaan/store', 'PesananController@BBPerusahaanStore')->name('pesanan.bb.perusahaan.store');

        Route::get('/bb-konsumen/create/{kode}', 'PesananController@BBKonsumenCreate')->name('pesanan.bb.konsumen.create');
        Route::post('/bb-konsumen/store', 'PesananController@BBKonsumenStore')->name('pesanan.bb.konsumen.store');

        Route::get('/cetak/{id}', 'PesananController@cetak')->name('pesanan.cetak');
    });

    Route::group(['prefix' => 'pengadaan', 'middleware' => ['level:pegawai', 'jabatan:admin|manager|gudang|purchasing']], function() {
        Route::get('/', 'PengadaanController@index')->name('pengadaan.index');
        Route::get('/pesanan', 'PengadaanController@indexPesanan')->name('pengadaan.index-pesanan');
        Route::get('/detail/{id}', 'PengadaanController@detail')->name('pengadaan.detail');
        Route::get('/setujui/{id}', 'PengadaanController@setujui')->name('pengadaan.setujui');
        Route::get('/tolak/{id}', 'PengadaanController@tolak')->name('pengadaan.tolak');
        Route::get('/create/', 'PengadaanController@create')->name('pengadaan.create');
        Route::post('/store/', 'PengadaanController@store')->name('pengadaan.store');
    });

    Route::get('/profile', 'ProfileController@form')->name('profile');
    Route::put('/profile', 'ProfileController@update');


    Route::group(['prefix' => 'penjualan', 'middleware' => ['level:supplier']], function() {
        Route::get('/', 'PenjualanBahanBakuController@index')->name('supplier.penjualan.index');
        Route::get('/pengiriman', 'PenjualanBahanBakuController@pengiriman')->name('supplier.pengiriman');
        Route::get('/{id}', 'PenjualanBahanBakuController@kirim')->name('supplier.penjualan.kirim');
    });

    Route::group(['prefix' => 'produksi', 'middleware' => ['level:pegawai|konsumen', 'jabatan:admin|produksi|gudang']], function() {
        Route::get('/', 'ProduksiController@index')->name('produksi.index');
        Route::get('/pesanan/{id}', 'ProduksiController@indexPesanan')->name('produksi.index-pesanan');
        Route::get('/detail/{id}', 'ProduksiController@detail')->name('produksi.detail');
        Route::get('/setujui/{id}', 'ProduksiController@setujui')->name('produksi.setujui');
        Route::get('/selesai/{id}', 'ProduksiController@selesai')->name('produksi.selesai');
        Route::get('/create/{id}', 'ProduksiController@create')->name('produksi.create');
        Route::post('/store/{id}', 'ProduksiController@store')->name('produksi.store');
    });

    Route::group(['prefix' => 'pengiriman'], function () {
        Route::get('/', 'PengirimanController@index')->name('pengiriman.index');
        Route::get('/pesanan/{id}', 'PengirimanController@indexPesanan')->name('pengiriman.pesanan');
        Route::get('/create/{id}', 'PengirimanController@create')->name('pengiriman.create');
        Route::post('/store/{id}', 'PengirimanController@store')->name('pengiriman.store');
        Route::get('/proses/{id}', 'PengirimanController@proses')->name('pengiriman.proses');
        Route::post('/update/{id}', 'PengirimanController@update')->name('pengiriman.update');
        Route::get('/terima/{id}', 'PengirimanController@terima')->name('pengiriman.terima');
        Route::get('/request/{id}', 'PengirimanController@requestPengiriman')->name('pengiriman.request');
        Route::get('/cetak/{id}', 'PengirimanController@cetakSJ')->name('pengiriman.cetaksj');
    });

    Route::group(['prefix' => 'laporan'], function () {
        Route::get('/pesanan', 'LaporanController@pesanan')->name('laporan.pesanan');
        Route::post('/pesanan/cetak', 'LaporanController@pesananCetak')->name('laporan.pesanan.cetak');
        Route::get('/pengiriman', 'LaporanController@pengiriman')->name('laporan.pengiriman');
        Route::post('/pengiriman/cetak', 'LaporanController@pengirimanCetak')->name('laporan.pengiriman.cetak');
        Route::get('/pengadaan', 'LaporanController@pengadaan')->name('laporan.pengadaan');
        Route::post('/pengadaan/cetak', 'LaporanController@pengadaanCetak')->name('laporan.pengadaan.cetak');
    });


    Route::get('/', function() {
        return redirect()->route('index');
    });


});

app/BOM.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class BOM extends Model
{
    protected $table = 'bom';

    public $timestamps = false;

    public function produk()
    {
    	return $this->belongsTo('App\Produk', 'kode_produk');
    }

    public function bahanBaku()
    {
    	return $this->belongsTo('App\BahanBaku', 'kode_bahan_baku');
    }
}

app/Http/Controllers/BOMController.php
<?php

namespace App\Http\Controllers;

use App\{BOM, Produk, BahanBaku};
use Illuminate\Http\Request;

use Exception, DB;

class BOMController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $param = $request->filter;

        if(!empty($request->filter['produk'])){
            $boms = BOM::where('kode_produk', $request->filter['produk'])->paginate(10);
        }else{
            $boms = BOM::paginate(10);
        }  

        $produks = Produk::where('status', 1)->get();

        return view('bom.index', compact('boms', 'produks', 'param'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $produks = Produk::where('status', 1)->get();

        $bahanBakus = BahanBaku::get();

        $jenis = ['Benang Lusi', 'Benang Pakan','Obat Kanji'];

        return view('bom.create', compact('produks', 'bahanBakus', 'jenis'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $produk = Produk::where('kode_produk', $request->produk)->first();

        DB::beginTransaction();
        try {

            $old = [];

            for ($i=0; $i < count($request->bahan_baku) ; $i++) { 

                $cek = BOM::where('kode_produk', $produk->kode_produk)
                        ->where('kode_bahan_baku', $request->bahan_baku[$i])
                        ->count();
                // if ($cek > 0 || in_array($request->bahan_baku[$i], $old)){
                //     throw new Exception("Bahan Baku Tidak Boleh Duplikat");
                // }

                if (intVal($request->jumlah[$i]) < 0){
                    throw new Exception("Jumlah (takaran tidak boleh kosong)");
                }

                $bom = new BOM;
                
                $bom->kode_produk = $produk->kode_produk;
                $bom->kode_bahan_baku = $request->bahan_baku[$i];
                $bom->jenis = $request->jenis[$i];
                $bom->jumlah = $request->jumlah[$i];

                $bom->save();
                $old[] = $request->bahan_baku[$i];

            }
            
            DB::commit();

        } catch (Exception $e) {
            DB::rollBack();
            return redirect()->back()->withInput()->with('alert-error', $e->getMessage());
        }

        return redirect()->route('bom.index')
                ->withInput()
                ->with('alert-success', 'Berhasil menambah BOM!');

        
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\BOM  $bom
     * @return \Illuminate\Http\Response
     */
    public function show(BOM $bom)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\BOM  $bom
     * @return \Illuminate\Http\Response
     */
    public function edit(BOM $bom)
    {
        $produk = Produk::where('kode_produk', $bom->kode_produk)->first();

        $bahanBaku = BahanBaku::findOrFail($bom->kode_bahan_baku);

        return view('bom.edit', compact('bom', 'produk', 'bahanBaku'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\BOM  $bom
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, BOM $bom)
    {
        $this->validate($request, [
            'jumlah'    => 'required'
        ]);

        $bom->jumlah = $request->jumlah;
        $bom->save();

        return redirect()->route('bom.index')->with('alert-success', 'Berhasil mengubah BOM!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\BOM  $bom
     * @return \Illuminate\Http\Response
     */
    public function destroy(BOM $bom)
    {
        DB::beginTransaction();
        try {

            $bom->delete();

            DB::commit();

        } catch (Exception $e) {

            DB::rollBack();
            return redirect()->back()->withInput()->with('alert-error', $e->getMessage());

        }

        return redirect()->route('bom.index')->with('alert-success', 'Berhasil menghapus BOM!');
    }

    public function getAjax(Request $request){
        $boms = BOM::join('bahan_baku', 'bom.kode_bahan_baku', 'bahan_baku.kode_bahan_baku')->select('bom.id', 'bom.jenis', 'bahan_baku.nama')->where('bom.kode_produk', $request->id)->get();

        return response()->json(['success' => true, 'data' => $boms]);
    }
}

resources/views/bom/create.blade.php
@extends('layouts.app')

@section('css')
<link rel="stylesheet" type="text/css" href="{{ asset('guru/default/assets/pages/j-pro/css/demo.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('guru/default/assets/pages/j-pro/css/font-awesome.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('guru/default/assets/pages/j-pro/css/j-pro-modern.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('guru/default/assets/pages/j-pro/css/j-forms.css') }}">
@endsection

@section('content')
<div class="page-header card">
    <div class="row align-items-end">
        <div class="col-lg-8">
            <div class="page-header-title">
                <i class="icofont icofont-layers bg-c-green"></i>
                <div class="d-inline">
                    <h4>Tambah Data BOM</h4>
                    <span></span>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="page-header-breadcrumb">
                <ul class="breadcrumb-title">
                    <li class="breadcrumb-item">
                        <a href="{{ route('index') }}">
                            <i class="icofont icofont-home"></i>
                        </a>
                    </li>
                    <li class="breadcrumb-item"><a href="{{ route('bom.index') }}">BOM</a>
                    </li>
                    <li class="breadcrumb-item"><a href="#">Tambah BOM</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="page-body">
    <div class="row">
        <div class="col-sm-12">
            <!-- clone elements card start -->
            <div class="card">
                <div class="card-block">
                    <div class="wrapper wrapper-640">
                        <form action="{{ route('bom.store') }}" method="POST" class="j-forms j-pro" id="j-forms" novalidate>
                            @csrf
                            <!-- end /.header-->
                            <div class="content">
                                <div class="j-unit">
                                    <label class="j-label">Produk</label>
                                    <div class="j-input ">
                                        <label class="input select" id="show-elements-select">
                                                <select name="produk">
                                                     @foreach ($produks as $produk)
                                                        <option value="{{$produk->kode_produk}}" {{ !empty($param['produk']) ? ($produk->kode_produk == $param['produk'] ? 'selected' : '') : '' }}>{{$produk->nama}}</option>
                                                    @endforeach
                                                </select>
                                        </label>
                                    </div>
                                </div>
                                @foreach ($jenis as $j)
                                <div class="span4 j-unit">
                                    <label class="j-label">Jenis</label>
                                    <div class="j-input">
                                        <label class="j-icon-right" for="jumlah">
                                            <i class="icofont icofont-law"></i>
                                        </label>
                                        <input type="text" id="jenis" name="jenis[]" value="{{ $j }}" readonly="">
                                    </div>
                                </div>
                                <div class="span5 j-unit">
                                    <label class="j-label">Bahan Baku</label>
                                    <div class="j-input ">
                                        <label class="input select" id="show-elements-select">
                                                <select name="bahan_baku[]">
                                                     @foreach ($bahanBakus as $bahanBaku)
                                                        <option value="{{$bahanBaku->kode_bahan_baku}}" selected>
                                                            {{$bahanBaku->nama}}
                                                        </option>
                                                    @endforeach
                                                </select>
                                        </label>
                                    </div>
                                </div>
                                <div class="span3 j-unit">
                                    <label class="j-label">Jumlah (takaran)</label>
                                    <div class="j-input">
                                        <label class="j-icon-right" for="jumlah">
                                            <i class="icofont icofont-law"></i>
                                        </label>
                                        <input type="text" id="jumlah" name="jumlah[]">
                                    </div>
                                </div>
                                @endforeach
                            </div>
                            <!-- end /.content -->
                            <div class="footer">
                                <button type="submit" class="btn btn-primary m-b-0">Simpan</button>
                            </div>
                            <!-- end /.footer -->
                        </form>
                    </div>
                </div>
            </div>
            <!-- clone elements card end -->
        </div>
    </div>
</div>

<form action="" method="POST" id="deleteForm">
    @csrf
    @method('DELETE')
    <input type="submit" style="display: none;">
</form>
@endsection

@section('js')

    <script type="text/javascript" src="{{ asset('guru/default/assets/pages/j-pro/js/jquery-cloneya.min.js') }}"></script>
<script type="text/javascript">
$('button#delete').on('click', function(){
    var href = $(this).attr('href');
    var title = $(this).data('title');
    swal({
      title: "Anda yakin akan menghapus bom bernama "+ title +" ?",
      text: "Setelah dihapus data tidak dapat dikembalikan !",
      icon: "warning",
      buttons: true,
      dangerMode: true,
    })
    .then((willDelete) => {
      if (willDelete) {
        $('#deleteForm').attr('action', href);
        $('#deleteForm').submit();
      }
    });
});

$(document).ready(function(){

        /***************************************/
        /* Cloned element */
        /***************************************/
        $('.clone-widget').cloneya();

        $('.clone-rightside-btn-1').cloneya();

        $('.clone-rightside-btn-2').cloneya();

        $('.clone-leftside-btn-1').cloneya();

        $('.clone-leftside-btn-2').cloneya();

        $('.clone-link').cloneya();
        /***************************************/
        /* end Cloned element */
        /***************************************/

    });
</script>
@endsection

resources/views/bom/edit.blade.php
@extends('layouts.app')

@section('css')
<link rel="stylesheet" type="text/css" href="{{ asset('guru/default/assets/pages/j-pro/css/demo.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('guru/default/assets/pages/j-pro/css/font-awesome.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('guru/default/assets/pages/j-pro/css/j-pro-modern.css') }}">
@endsection

@section('content')
<div class="page-header card">
    <div class="row align-items-end">
        <div class="col-lg-8">
            <div class="page-header-title">
                <i class="icofont icofont-layers bg-c-green"></i>
                <div class="d-inline">
                    <h4>Edit Data BOM</h4>
                    <span></span>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="page-header-breadcrumb">
                <ul class="breadcrumb-title">
                    <li class="breadcrumb-item">
                        <a href="{{ route('index') }}">
                            <i class="icofont icofont-home"></i>
                        </a>
                    </li>
                    <li class="breadcrumb-item"><a href="{{ route('bom.index') }}">BOM</a>
                    </li>
                    <li class="breadcrumb-item"><a href="#">Edit BOM</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="page-body">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-block">
                    <div class="j-wrapper j-wrapper-640">
                        <form action="{{ route('bom.update', $bom) }}" method="post" class="j-pro" id="j-pro" novalidate="" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="j-content">
                                <!-- start name -->
                                <div class="j-unit">
                                    <label class="j-label">Produk</label>
                                        <div class="j-input ">
                                            <label class="input select" id="show-elements-select">
                                                    <select name="produk" readonly>
                                                            <option value="{{$produk->kode_produk}}" {{ !empty($param['produk']) ? ($produk->kode_produk == $param['produk'] ? 'selected' : '') : '' }}>{{$produk->nama}}</option>
                                                    </select>
                                            </label>
                                        </div>
                                </div>
                                <!-- end name -->

                                <!-- start email phone -->
                                <div class="j-row">
                                    <div class="j-span6 j-unit">
                                        <label class="j-label">Bahan Baku</label>
                                        <div class="j-input">
                                            <input type="text" value="{{ $bahanBaku->nama }}" readonly="">
                                        </div>
                                    </div>
                                    <div class="j-span6 j-unit">
                                        <label class="j-label">Jumlah (takaran)</label>
                                        <div class="j-input {{ $errors->has('jumlah') ? 'j-error-view' : '' }}">
                                            <label class="j-icon-right" for="jumlah">
                                                <i class="icofont icofont-law"></i>
                                            </label>
                                            <input type="text" id="jumlah" name="jumlah" value="{{ old('jumlah') ?? $bom->jumlah }}">
                                            @if ( $errors->has('jumlah') )
                                                <span class="j-error-view">{{$errors->first('jumlah')}}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                                <div class="j-divider j-gap-bottom-25"></div>
                            </div>
                            <!-- end /.content -->
                            <div class="j-footer">
                                <button type="submit" class="btn btn-primary">Simpan</button>
                            </div>
                            <!-- end /.footer -->
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<form action="" method="POST" id="deleteForm">
    @csrf
    @method('DELETE')
    <input type="submit" style="display: none;">
</form>
@endsection

@section('js')
<script type="text/javascript">
$('button#delete').on('click', function(){
    var href = $(this).attr('href');
    var title = $(this).data('title');
    swal({
      title: "Anda yakin akan menghapus bom bernama "+ title +" ?",
      text: "Setelah dihapus data tidak dapat dikembalikan !",
      icon: "warning",
      buttons: true,
      dangerMode: true,
    })
    .then((willDelete) => {
      if (willDelete) {
        $('#deleteForm').attr('action', href);
        $('#deleteForm').submit();
      }
    });
});
</script>
@endsection

resources/views/bom/index.blade.php
@extends('layouts.app')

@section('content')
<div class="page-header card">
    <div class="row align-items-end">
        <div class="col-lg-8">
            <div class="page-header-title">
                <i class="icofont icofont-layers bg-c-green"></i>
                <div class="d-inline">
                    <h4>Kelola Data BOM</h4>
                    <span>Tambah Data BOM, Ubah Data BOM dan Hapus Data BOM</span>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="page-header-breadcrumb">
                <ul class="breadcrumb-title">
                    <li class="breadcrumb-item">
                        <a href="{{ route('index') }}">
                            <i class="icofont icofont-home"></i>
                        </a>
                    </li>
                    <li class="breadcrumb-item"><a href="{{ route('bom.index') }}">BOM</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="page-body">
    <div class="card">
        <div class="card-header">
            <a href="{{ route('bom.create') }}"><button class="btn btn-sm btn-primary">Tambah BOM</button></a>
        </div>
        <div class="card-block table-border-style">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Nama Produk</th>
                            <th>Jenis</th>
                            <th>Bahan Baku</th>
                            <th>Jumlah (takaran)</th>
                            <th>#</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr style="background:#e9ecef">
                            <form action="" method="GET" name="search_form" id="search_form">
                            <td>
                                <select class="form-control" name="filter[produk]">
                                    <option value="">Semua</option>
                                    @foreach ($produks as $produk)
                                        <option value="{{$produk->kode_produk}}" {{ !empty($param['produk']) ? ($produk->kode_produk == $param['produk'] ? 'selected' : '') : '' }}>[{{$produk->kode_produk}}] - {{$produk->nama}}</option>
                                    @endforeach
                                </select>
                            </td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td>
                                <button type="submit" class="btn btn-info btn-bordered btn-sm">Cari
                                </button>
                                <button type="reset" onclick="javascript:window.location.assign('{{ route('bom.index') }}');" class="btn btn-info btn-bordered btn-sm">
                                    Reset
                                </button>
                            </td>
                            </form>
                        </tr>
                    @foreach ($boms as $bom)
                        <tr>
                            <td>{{ $bom->produk->nama }}</td>
                            <td>{{ $bom->jenis }}</td>
                            <td>{{ $bom->bahanBaku->nama }}</td>
                            <td>{{ $bom->jumlah }}</td>
                            <td>
                                <a href="{{ route('bom.edit', $bom) }}">
                                    <button class="btn btn-mini btn-warning">Edit</button>
                                </a>
                                <button id="delete" href="{{ route('bom.destroy', $bom) }}" class="btn btn-mini btn-danger">Hapus</button>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <div style="padding: 15px;width: 100%">
                    <center>{{ $boms->appends(request()->except('page'))->links() }}</center>
                </div>
            </div>
        </div>
    </div>
</div>

<form action="" method="POST" id="deleteForm">
    @csrf
    @method('DELETE')
    <input type="submit" style="display: none;">
</form>
@endsection

@section('js')
<script type="text/javascript">
$('button#delete').on('click', function(){
    var href = $(this).attr('href');
    var title = $(this).data('title');
    swal({
      title: "Anda yakin akan menghapus BOM ini ?",
      text: "Setelah dihapus data tidak dapat dikembalikan !",
      icon: "warning",
      buttons: true,
      dangerMode: true,
    })
    .then((willDelete) => {
      if (willDelete) {
        $('#deleteForm').attr('action', href);
        $('#deleteForm').submit();
      }
    });
});
</script>
@endsection