routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('tes', 'HomeController@tes');

Auth::routes();

Route::get('/register', function(){
   return "Disable"; 
});
Route::get('/logout', 'Auth\LoginController@logout')->name('logout')->middleware(['auth']);



Route::group(['middleware' => 'auth'], function(){

    Route::get('/home', 'HomeController@index')->name('index')->middleware(['level:pegawai|konsumen|supplier']);

    Route::resource('pegawai', 'PegawaiController')->middleware(['level:pegawai','jabatan:admin']);
    Route::resource('konsumen', 'KonsumenController')->middleware(['level:pegawai','jabatan:admin|manager']);
    Route::resource('produk', 'ProdukController')->middleware(['level:pegawai','jabatan:admin|manager|produksi|gudang']);
    Route::resource('supplier', 'SupplierController')->middleware(['level:pegawai','jabatan:admin|manager|purchasing']);
    Route::resource('kendaraan', 'KendaraanController')->middleware(['level:pegawai','jabatan:admin|manager|distribusi']);
    Route::get('kendaraan/switch/{id}', 'KendaraanController@switchStatus')->name('kendaraan.switch');

    Route::resource('bahan-baku-supplier', 'BahanBakuSupplierController')->middleware(['level:pegawai|supplier','jabatan:admin|manager|gudang|purchasing']);

    Route::group(['prefix' => 'bahan-baku/penerimaan', 'middleware' => ['level:pegawai','jabatan:admin|manager|gudang']], function() {
        Route::get('/', 'BahanBakuController@penerimaan')->name('penerimaan.index');
        Route::get('/terima/{id}', 'BahanBakuController@terima')->name('penerimaan.terima');
    });
    Route::resource('bahan-baku', 'BahanBakuController')->middleware(['level:pegawai','jabatan:admin|manager|gudang|supplier|distribusi|purchasing']);

    Route::get('/bom/get-ajax', 'BOMController@getAjax')->name('bom.ajax');
    Route::resource('bom', 'BOMController')->middleware(['level:pegawai','jabatan:admin|manager|produksi']);

    Route::group(['prefix' => 'pesanan', 'middleware' => ['level:pegawai|konsumen', 'jabatan:admin|manager|produksi']], function() {
        Route::get('/proses/{id}', 'PesananController@proses')->name('pesanan.proses');
    	Route::get('/tolak/{id}', 'PesananController@tolak')->name('pesanan.tolak');
    	Route::get('/selesai/{id}', 'PesananController@selesai')->name('pesanan.selesai');
    	Route::get('/detail/{id}', 'PesananController@detail')->name('pesanan.detail');

        Route::get('/index', 'PesananController@index')->name('pesanan.index');

        Route::get('/design-baru', 'PesananDesignBaruController@index')->name('pesanan.design.baru.index');
        Route::get('/design-baru/create', 'PesananDesignBaruController@create')->name('pesanan.design.baru.create');
        Route::post('/design-baru/store', 'PesananDesignBaruController@store')->name('pesanan.design.baru.store');
        Route::get('/design-baru/proses/{id}', 'PesananDesignBaruController@proses')->name('pesanan.design.baru.proses');
        Route::get('/design-baru/tolak/{id}', 'PesananDesignBaruController@tolak')->name('pesanan.design.baru.tolak');
        Route::post('/design-baru/buat/{id}', 'PesananDesignBaruController@buatPesanan')->name('pesanan.design.baru.buat');

        Route::get('/{bb}/produk', 'PesananController@produk')->name('pesanan.produk');

        Route::get('/bb-perusahaan/create/{kode}', 'PesananController@BBPerusahaanCreate')->name('pesanan.bb.perusahaan.create');
        Route::post('/bb-perusahaan/store', 'PesananController@BBPerusahaanStore')->name('pesanan.bb.perusahaan.store');

        Route::get('/bb-konsumen/create/{kode}', 'PesananController@BBKonsumenCreate')->name('pesanan.bb.konsumen.create');
        Route::post('/bb-konsumen/store', 'PesananController@BBKonsumenStore')->name('pesanan.bb.konsumen.store');

        Route::get('/cetak/{id}', 'PesananController@cetak')->name('pesanan.cetak');
    });

    Route::group(['prefix' => 'pengadaan', 'middleware' => ['level:pegawai', 'jabatan:admin|manager|gudang|purchasing']], function() {
        Route::get('/', 'PengadaanController@index')->name('pengadaan.index');
        Route::get('/pesanan', 'PengadaanController@indexPesanan')->name('pengadaan.index-pesanan');
        Route::get('/detail/{id}', 'PengadaanController@detail')->name('pengadaan.detail');
        Route::get('/setujui/{id}', 'PengadaanController@setujui')->name('pengadaan.setujui');
        Route::get('/tolak/{id}', 'PengadaanController@tolak')->name('pengadaan.tolak');
        Route::get('/create/', 'PengadaanController@create')->name('pengadaan.create');
        Route::post('/store/', 'PengadaanController@store')->name('pengadaan.store');
    });

    Route::get('/profile', 'ProfileController@form')->name('profile');
    Route::put('/profile', 'ProfileController@update');


    Route::group(['prefix' => 'penjualan', 'middleware' => ['level:supplier']], function() {
        Route::get('/', 'PenjualanBahanBakuController@index')->name('supplier.penjualan.index');
        Route::get('/pengiriman', 'PenjualanBahanBakuController@pengiriman')->name('supplier.pengiriman');
        Route::get('/{id}', 'PenjualanBahanBakuController@kirim')->name('supplier.penjualan.kirim');
    });

    Route::group(['prefix' => 'produksi', 'middleware' => ['level:pegawai|konsumen', 'jabatan:admin|produksi|gudang']], function() {
        Route::get('/', 'ProduksiController@index')->name('produksi.index');
        Route::get('/pesanan/{id}', 'ProduksiController@indexPesanan')->name('produksi.index-pesanan');
        Route::get('/detail/{id}', 'ProduksiController@detail')->name('produksi.detail');
        Route::get('/setujui/{id}', 'ProduksiController@setujui')->name('produksi.setujui');
        Route::get('/selesai/{id}', 'ProduksiController@selesai')->name('produksi.selesai');
        Route::get('/create/{id}', 'ProduksiController@create')->name('produksi.create');
        Route::post('/store/{id}', 'ProduksiController@store')->name('produksi.store');
    });

    Route::group(['prefix' => 'pengiriman'], function () {
        Route::get('/', 'PengirimanController@index')->name('pengiriman.index');
        Route::get('/pesanan/{id}', 'PengirimanController@indexPesanan')->name('pengiriman.pesanan');
        Route::get('/create/{id}', 'PengirimanController@create')->name('pengiriman.create');
        Route::post('/store/{id}', 'PengirimanController@store')->name('pengiriman.store');
        Route::get('/proses/{id}', 'PengirimanController@proses')->name('pengiriman.proses');
        Route::post('/update/{id}', 'PengirimanController@update')->name('pengiriman.update');
        Route::get('/terima/{id}', 'PengirimanController@terima')->name('pengiriman.terima');
        Route::get('/request/{id}', 'PengirimanController@requestPengiriman')->name('pengiriman.request');
        Route::get('/cetak/{id}', 'PengirimanController@cetakSJ')->name('pengiriman.cetaksj');
    });

    Route::group(['prefix' => 'laporan'], function () {
        Route::get('/pesanan', 'LaporanController@pesanan')->name('laporan.pesanan');
        Route::post('/pesanan/cetak', 'LaporanController@pesananCetak')->name('laporan.pesanan.cetak');
        Route::get('/pengiriman', 'LaporanController@pengiriman')->name('laporan.pengiriman');
        Route::post('/pengiriman/cetak', 'LaporanController@pengirimanCetak')->name('laporan.pengiriman.cetak');
        Route::get('/pengadaan', 'LaporanController@pengadaan')->name('laporan.pengadaan');
        Route::post('/pengadaan/cetak', 'LaporanController@pengadaanCetak')->name('laporan.pengadaan.cetak');
    });


    Route::get('/', function() {
        return redirect()->route('index');
    });


});

app/Konsumen.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Konsumen extends Model
{
	protected $table = 'konsumen';

	public $timestamps = false;

    public function user()
    {
    	return $this->belongsTo('App\User');
    }

    public function pesanan()
    {
    	return $this->hasMany('App\Pesanan');
    }
}

app/Http/Controllers/KonsumenController.php
<?php

namespace App\Http\Controllers;

use App\{Konsumen, User};
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Image;
use Exception, DB;

class KonsumenController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $param = $request->filter;
        
        $konsumens = Konsumen::join('users', 'users.id', '=', 'konsumen.user_id')
                ->select('konsumen.id', 'users.nama', 'users.email', 'users.kontak', 'users.alamat')
                ->where('users.nama', 'like', '%' . ($request->filter['nama'] ?? '')  . '%')
                ->where('users.email', 'like', '%' . ($request->filter['email'] ?? '') . '%')
                ->where('users.kontak', 'like', '%' . ($request->filter['kontak'] ?? '') . '%')
                ->where('users.alamat', 'like', '%' . ($request->filter['alamat'] ?? '')  . '%')
                ->paginate(10);

        return view('konsumen.index', compact('konsumens', 'param'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('konsumen.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|min:4|max:50|alpha',
            'email' => 'email|unique:users,email',
            'password' => 'required|string|min:6',
            'kontak' => 'required|numeric',
            'foto'  => 'nullable|image',
            'alamat' => 'required|string|max:200',
        ]);

        $imgname = Null;
        if( !is_null($request->foto) ){
            $imageLocation = public_path('images/foto').'/';
            
            $imgname = 'konsumen-'.time().'.'.$request->foto->getClientOriginalExtension();
            Image::make($request->foto)->resize(300, 300)
                    ->save($imageLocation .$imgname);
        }

        DB::beginTransaction();
        try {

            $user = new User;
            $user->nama = $request->name;
            $user->email = $request->email;
            $user->password = bcrypt($request->password);
            $user->jenis_kelamin = $request->jeniskelamin;
            $user->alamat = $request->alamat ?? '-';
            $user->kontak = $request->kontak ?? '-';
            $user->foto = $imgname;
            $user->save();

            $konsumen = New Konsumen;
            $user->konsumen()->save($konsumen);

            DB::commit();

        } catch (Exception $e) {

            DB::rollBack();
            return redirect()->back()->withInput()->with('alert-error', $e->getMessage());

        }


        return redirect()->route('konsumen.index')->with('alert-success', 'Berhasil menambah konsumen!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $konsumen = Konsumen::findOrFail($id);

        return view('konsumen.edit', compact('konsumen', 'jabatans'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $konsumen = Konsumen::findOrFail($id);

        $user = User::findOrFail($konsumen->user_id);

        $this->validate($request, [
            'name' => 'required|min:4|max:50|alpha',
            'email' => [
                'required',
                'email',
                Rule::unique('users')->ignore($user->id),
            ],
            'password' => 'nullable|string|min:6',
            'kontak' => 'required|numeric',
            'foto'  => 'nullable|image',
            'alamat' => 'required|string|max:200'
        ]);

        DB::beginTransaction();
        try {

            $imgname = Null;

            if( !is_null($request->foto) ){
                $imageLocation = public_path('images/foto').'/';

                $img = $user->foto;
                !file_exists($imageLocation.$img) or unlink($imageLocation.$img);

                $imgname = 'konsumen-'.time().'.'.$request->foto->getClientOriginalExtension();
                Image::make($request->foto)->resize(300, 300)
                        ->save($imageLocation .$imgname);
            }
            
            $konsumen->save();

            $user->nama = $request->name;
            $user->email = $request->email;
            if(!is_null($request->password))
                $user->password = bcrypt($request->password);
            $user->jenis_kelamin = $request->jeniskelamin;
            $user->alamat = $request->alamat ?? '-';
            $user->kontak = $request->kontak ?? '-';
            $user->foto = $imgname;
            $user->save();

            DB::commit();

        } catch (Exception $e) {

            DB::rollBack();
            return redirect()->back()->withInput()->with('alert-error', $e->getMessage());

        }

        return redirect()->route('konsumen.index')->with('alert-success', 'Berhasil mengubah konsumen!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $konsumen = Konsumen::findOrFail($id);
        $user = User::findOrFail($konsumen->user_id);

        $img = $user->foto;

        DB::beginTransaction();
        try {

            
            $konsumen->delete();
            $user->delete();

            DB::commit();

        } catch (Exception $e) {

            DB::rollBack();
            return redirect()->back()->withInput()->with('alert-error', $e->getMessage());

        }

        $imageLocation = public_path('images/foto').'/';
        if (!is_null($img)) !file_exists($imageLocation.$img) or unlink($imageLocation.$img);

        return redirect()->back()->with('alert-success', 'Berhasil menghapus data konsumen.');
    }
}

resources/views/konsumen/edit.blade.php
@extends('layouts.app')

@section('css')
<link rel="stylesheet" type="text/css" href="{{ asset('guru/default/assets/pages/j-pro/css/demo.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('guru/default/assets/pages/j-pro/css/font-awesome.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('guru/default/assets/pages/j-pro/css/j-pro-modern.css') }}">
@endsection

@section('content')
<div class="page-header card">
    <div class="row align-items-end">
        <div class="col-lg-8">
            <div class="page-header-title">
                <i class="icofont icofont-user bg-c-green"></i>
                <div class="d-inline">
                    <h4>Edit Data Konsumen</h4>
                    <span></span>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="page-header-breadcrumb">
                <ul class="breadcrumb-title">
                    <li class="breadcrumb-item">
                        <a href="{{ route('index') }}">
                            <i class="icofont icofont-home"></i>
                        </a>
                    </li>
                    <li class="breadcrumb-item"><a href="{{ route('konsumen.index') }}">Konsumen</a>
                    </li>
                    <li class="breadcrumb-item"><a href="#">Edit Konsumen</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="page-body">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-block">
                    <div class="j-wrapper j-wrapper-640">
                        <form action="{{ route('konsumen.update', $konsumen) }}" method="post" class="j-pro" id="j-pro" novalidate="" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="j-content">
                                <!-- start name -->
                                <div class="j-unit">
                                    <label class="j-label">Nama Lengkap</label>
                                    <div class="j-input {{ $errors->has('name') ? ' j-error-view' : '' }}">
                                        <label class="j-icon-right" for="name">
                                            <i class="icofont icofont-ui-user"></i>
                                        </label>
                                        <input type="text" id="name" name="name" value="{{ old('name') ?? $konsumen->user->nama }}">
                                        @if ( $errors->has('name') )
                                            <span class="j-error-view">{{$errors->first('name')}}</span>
                                        @endif
                                    </div>
                                </div>
                                <!-- end name -->

                                <!-- start email phone -->
                                <div class="j-row">
                                    <div class="j-span6 j-unit">
                                        <label class="j-label">Email</label>
                                        <div class="j-input {{ $errors->has('email') ? ' j-error-view' : '' }}">
                                            <label class="j-icon-right" for="email">
                                                <i class="icofont icofont-envelope"></i>
                                            </label>
                                            <input type="email" id="email" name="email" value="{{ old('email') ?? $konsumen->user->email }}">
                                        @if ( $errors->has('email') )
                                            <span class="j-error-view">{{$errors->first('email')}}</span>
                                        @endif
                                        </div>
                                    </div>
                                    <div class="j-span6 j-unit">
                                        <label class="j-label">Password</label>
                                        <div class="j-input {{ $errors->has('password') ? ' j-error-view' : '' }}"">
                                            <label class="j-icon-right" for="password">
                                                <i class="icofont icofont-key"></i>
                                            </label>
                                            <input type="password" id="password" name="password" placeholder="Kosongkan jika tidak ingin diubah">
                                        @if ( $errors->has('password') )
                                            <span class="j-error-view">{{$errors->first('password')}}</span>
                                        @endif
                                        </div>
                                    </div>
                                </div>
                                <!-- end email phone -->
                                <div class="j-divider j-gap-bottom-25"></div>

                                <!-- start date -->
                                <div class="j-row">
                                    <div class="j-span6 j-unit">
                                        <label class="j-label">Jenis Kelamin</label>
                                        <div class="j-input">
                                            <label class="input select" id="show-elements-select">
                                                <select name="jeniskelamin">
                                                   <option value="Laki-Laki" {{ old('jeniskelamin') ?? $konsumen->user->jenis_kelamin == 'Laki-Laki' ? 'selected' : ''}}>Laki-Laki</option>
                                                   <option value="Perempuan" {{ old('jeniskelamin') ?? $konsumen->user->jenis_kelamin == 'Perempuan' ? 'selected' : ''}}>Perempupan</option>
                                                </select>
                                                <i></i>
                                            </label>
                                        </div>
                                    </div>
                                    <div class="j-span6 j-unit">
                                        <label class="j-label">Kontak</label>
                                        <div class="j-input {{ $errors->has('kontak') ? ' j-error-view' : '' }}"">
                                            <label class="j-icon-right" for="kontak">
                                                <i class="icofont icofont-phone"></i>
                                            </label>
                                            <input type="text" id="kontak" name="kontak" value="{{ old('kontak') ?? $konsumen->user->kontak }}">
                                        @if ( $errors->has('kontak') )
                                            <span class="j-error-view">{{$errors->first('kontak')}}</span>
                                        @endif
                                        </div>
                                    </div>
                                </div>
                                <div class="j-unit">
                                    <div class="j-input j-append-small-btn {{ $errors->has('foto') ? ' j-error-view' : '' }}">
                                        <div class="j-file-button">
                                            Browse
                                            <input type="file" id="file2" name="foto" onchange="document.getElementById('file2_input').value = this.value;">
                                        </div>
                                        <input type="text" id="file2_input" readonly="" placeholder="Kosongkan jika tidak ingin diubah">
                                        <span class="j-hint">Ukuran foto 512x512px / 300x300px </span>
                                        @if ( $errors->has('foto') )
                                            <span class="j-error-view">{{$errors->first('foto')}}</span>
                                        @endif
                                    </div>
                                </div>
                                <!-- end date -->
                                <div class="j-divider j-gap-bottom-25"></div>
                                <!-- start message -->
                                <div class="j-unit">
                                    <label class="j-label">Alamat</label>
                                    <div class="j-input {{ $errors->has('alamat') ? ' j-error-view' : '' }}"">
                                        <textarea spellcheck="false" name="alamat">{{ old('alamat') ?? $konsumen->user->alamat }}</textarea>
                                        @if ( $errors->has('alamat') )
                                            <span class="j-error-view">{{$errors->first('alamat')}}</span>
                                        @endif
                                    </div>
                                </div>
                                <!-- end message -->
                                <!-- start response from server -->
                                <div class="j-response"></div>
                                <!-- end response from server -->
                            </div>
                            <!-- end /.content -->
                            <div class="j-footer">
                                <button type="submit" class="btn btn-primary">Simpan</button>
                            </div>
                            <!-- end /.footer -->
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<form action="" method="POST" id="deleteForm">
    @csrf
    @method('DELETE')
    <input type="submit" style="display: none;">
</form>
@endsection

@section('js')
<script type="text/javascript">
$('button#delete').on('click', function(){
    var href = $(this).attr('href');
    var title = $(this).data('title');
    swal({
      title: "Anda yakin akan menghapus konsumen bernama "+ title +" ?",
      text: "Setelah dihapus data tidak dapat dikembalikan !",
      icon: "warning",
      buttons: true,
      dangerMode: true,
    })
    .then((willDelete) => {
      if (willDelete) {
        $('#deleteForm').attr('action', href);
        $('#deleteForm').submit();
      }
    });
});
</script>
@endsection

resources/views/konsumen/index.blade.php
@extends('layouts.app')

@section('content')
<div class="page-header card">
    <div class="row align-items-end">
        <div class="col-lg-8">
            <div class="page-header-title">
                <i class="icofont icofont-user bg-c-green"></i>
                <div class="d-inline">
                    <h4>Kelola Data Konsumen</h4>
                    <span>Tambah Data Konsumen, Ubah Data Konsumen dan Hapus Data Konsumen</span>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="page-header-breadcrumb">
                <ul class="breadcrumb-title">
                    <li class="breadcrumb-item">
                        <a href="{{ route('index') }}">
                            <i class="icofont icofont-home"></i>
                        </a>
                    </li>
                    <li class="breadcrumb-item"><a href="{{ route('konsumen.index') }}">Konsumen</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="page-body">
    <div class="card">
        <div class="card-header">
            <a href="{{ route('konsumen.create') }}"><button class="btn btn-sm btn-primary">Tambah Konsumen</button></a>
        </div>
        <div class="card-block table-border-style">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Nama</th>
                            <th>Kontak</th>
                            <th>Email</th>
                            <th>Alamat</th>
                            <th>#</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr style="background:#e9ecef">
                            <form action="" method="GET" name="search_form" id="search_form">
                            <td>
                                <input type="text" class="form-control form-control-sm" name="filter[nama]" value="{{ $param['nama'] ?? '' }}">
                            </td>
                            <td>
                                <input type="text" class="form-control form-control-sm" name="filter[kontak]" value="{{ $param['kontak'] ?? ''}}">
                            </td>
                            <td>
                                <input type="text" class="form-control form-control-sm" name="filter[email]" value="{{ $param['email'] ?? ''}}">
                            </td>
                            <td>
                                <input type="text" class="form-control form-control-sm" name="filter[alamat]" value="{{ $param['alamat'] ?? ''}}">
                            </td>
                            <td>
                                <button type="submit" class="btn btn-info btn-bordered btn-sm">Cari
                                </button>
                                <button type="reset" onclick="javascript:window.location.assign('{{ route('konsumen.index') }}');" class="btn btn-info btn-bordered btn-sm">
                                    Reset
                                </button>
                            </td>
                            </form>
                        </tr>
                    @foreach ($konsumens as $konsumen)
                        <tr>
                            <td>{{ $konsumen->nama }}</td>
                            <td>{{ $konsumen->kontak }}</td>
                            <td>{{ $konsumen->email }}</td>
                            <td>{{ $konsumen->alamat }}</td>
                            <td>
                                <a href="{{ route('konsumen.edit', $konsumen) }}">
                                    <button class="btn btn-mini btn-warning">Edit</button>
                                </a>
                                <button id="delete" data-title="{{$konsumen->nama}}" href="{{ route('konsumen.destroy', $konsumen) }}" class="btn btn-mini btn-danger">Hapus</button>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <div style="padding: 15px;width: 100%">
                    <center>{{ $konsumens->appends(request()->except('page'))->links() }}</center>
                </div>
            </div>
        </div>
    </div>
</div>

<form action="" method="POST" id="deleteForm">
    @csrf
    @method('DELETE')
    <input type="submit" style="display: none;">
</form>
@endsection

@section('js')
<script type="text/javascript">
$('button#delete').on('click', function(){
    var href = $(this).attr('href');
    var title = $(this).data('title');
    swal({
      title: "Anda yakin akan menghapus konsumen bernama "+ title +" ?",
      text: "Setelah dihapus data tidak dapat dikembalikan !",
      icon: "warning",
      buttons: true,
      dangerMode: true,
    })
    .then((willDelete) => {
      if (willDelete) {
        $('#deleteForm').attr('action', href);
        $('#deleteForm').submit();
      }
    });
});
</script>
@endsection