routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('tes', 'HomeController@tes');

Auth::routes();

Route::get('/register', function(){
   return "Disable"; 
});
Route::get('/logout', 'Auth\LoginController@logout')->name('logout')->middleware(['auth']);



Route::group(['middleware' => 'auth'], function(){

    Route::get('/home', 'HomeController@index')->name('index')->middleware(['level:pegawai|konsumen|supplier']);

    Route::resource('pegawai', 'PegawaiController')->middleware(['level:pegawai','jabatan:admin']);
    Route::resource('konsumen', 'KonsumenController')->middleware(['level:pegawai','jabatan:admin|manager']);
    Route::resource('produk', 'ProdukController')->middleware(['level:pegawai','jabatan:admin|manager|produksi|gudang']);
    Route::resource('supplier', 'SupplierController')->middleware(['level:pegawai','jabatan:admin|manager|purchasing']);
    Route::resource('kendaraan', 'KendaraanController')->middleware(['level:pegawai','jabatan:admin|manager|distribusi']);
    Route::get('kendaraan/switch/{id}', 'KendaraanController@switchStatus')->name('kendaraan.switch');

    Route::resource('bahan-baku-supplier', 'BahanBakuSupplierController')->middleware(['level:pegawai|supplier','jabatan:admin|manager|gudang|purchasing']);

    Route::group(['prefix' => 'bahan-baku/penerimaan', 'middleware' => ['level:pegawai','jabatan:admin|manager|gudang']], function() {
        Route::get('/', 'BahanBakuController@penerimaan')->name('penerimaan.index');
        Route::get('/terima/{id}', 'BahanBakuController@terima')->name('penerimaan.terima');
    });
    Route::resource('bahan-baku', 'BahanBakuController')->middleware(['level:pegawai','jabatan:admin|manager|gudang|supplier|distribusi|purchasing']);

    Route::get('/bom/get-ajax', 'BOMController@getAjax')->name('bom.ajax');
    Route::resource('bom', 'BOMController')->middleware(['level:pegawai','jabatan:admin|manager|produksi']);

    Route::group(['prefix' => 'pesanan', 'middleware' => ['level:pegawai|konsumen', 'jabatan:admin|manager|produksi']], function() {
        Route::get('/proses/{id}', 'PesananController@proses')->name('pesanan.proses');
    	Route::get('/tolak/{id}', 'PesananController@tolak')->name('pesanan.tolak');
    	Route::get('/selesai/{id}', 'PesananController@selesai')->name('pesanan.selesai');
    	Route::get('/detail/{id}', 'PesananController@detail')->name('pesanan.detail');

        Route::get('/index', 'PesananController@index')->name('pesanan.index');

        Route::get('/design-baru', 'PesananDesignBaruController@index')->name('pesanan.design.baru.index');
        Route::get('/design-baru/create', 'PesananDesignBaruController@create')->name('pesanan.design.baru.create');
        Route::post('/design-baru/store', 'PesananDesignBaruController@store')->name('pesanan.design.baru.store');
        Route::get('/design-baru/proses/{id}', 'PesananDesignBaruController@proses')->name('pesanan.design.baru.proses');
        Route::get('/design-baru/tolak/{id}', 'PesananDesignBaruController@tolak')->name('pesanan.design.baru.tolak');
        Route::post('/design-baru/buat/{id}', 'PesananDesignBaruController@buatPesanan')->name('pesanan.design.baru.buat');

        Route::get('/{bb}/produk', 'PesananController@produk')->name('pesanan.produk');

        Route::get('/bb-perusahaan/create/{kode}', 'PesananController@BBPerusahaanCreate')->name('pesanan.bb.perusahaan.create');
        Route::post('/bb-perusahaan/store', 'PesananController@BBPerusahaanStore')->name('pesanan.bb.perusahaan.store');

        Route::get('/bb-konsumen/create/{kode}', 'PesananController@BBKonsumenCreate')->name('pesanan.bb.konsumen.create');
        Route::post('/bb-konsumen/store', 'PesananController@BBKonsumenStore')->name('pesanan.bb.konsumen.store');

        Route::get('/cetak/{id}', 'PesananController@cetak')->name('pesanan.cetak');
    });

    Route::group(['prefix' => 'pengadaan', 'middleware' => ['level:pegawai', 'jabatan:admin|manager|gudang|purchasing']], function() {
        Route::get('/', 'PengadaanController@index')->name('pengadaan.index');
        Route::get('/pesanan', 'PengadaanController@indexPesanan')->name('pengadaan.index-pesanan');
        Route::get('/detail/{id}', 'PengadaanController@detail')->name('pengadaan.detail');
        Route::get('/setujui/{id}', 'PengadaanController@setujui')->name('pengadaan.setujui');
        Route::get('/tolak/{id}', 'PengadaanController@tolak')->name('pengadaan.tolak');
        Route::get('/create/', 'PengadaanController@create')->name('pengadaan.create');
        Route::post('/store/', 'PengadaanController@store')->name('pengadaan.store');
    });

    Route::get('/profile', 'ProfileController@form')->name('profile');
    Route::put('/profile', 'ProfileController@update');


    Route::group(['prefix' => 'penjualan', 'middleware' => ['level:supplier']], function() {
        Route::get('/', 'PenjualanBahanBakuController@index')->name('supplier.penjualan.index');
        Route::get('/pengiriman', 'PenjualanBahanBakuController@pengiriman')->name('supplier.pengiriman');
        Route::get('/{id}', 'PenjualanBahanBakuController@kirim')->name('supplier.penjualan.kirim');
    });

    Route::group(['prefix' => 'produksi', 'middleware' => ['level:pegawai|konsumen', 'jabatan:admin|produksi|gudang']], function() {
        Route::get('/', 'ProduksiController@index')->name('produksi.index');
        Route::get('/pesanan/{id}', 'ProduksiController@indexPesanan')->name('produksi.index-pesanan');
        Route::get('/detail/{id}', 'ProduksiController@detail')->name('produksi.detail');
        Route::get('/setujui/{id}', 'ProduksiController@setujui')->name('produksi.setujui');
        Route::get('/selesai/{id}', 'ProduksiController@selesai')->name('produksi.selesai');
        Route::get('/create/{id}', 'ProduksiController@create')->name('produksi.create');
        Route::post('/store/{id}', 'ProduksiController@store')->name('produksi.store');
    });

    Route::group(['prefix' => 'pengiriman'], function () {
        Route::get('/', 'PengirimanController@index')->name('pengiriman.index');
        Route::get('/pesanan/{id}', 'PengirimanController@indexPesanan')->name('pengiriman.pesanan');
        Route::get('/create/{id}', 'PengirimanController@create')->name('pengiriman.create');
        Route::post('/store/{id}', 'PengirimanController@store')->name('pengiriman.store');
        Route::get('/proses/{id}', 'PengirimanController@proses')->name('pengiriman.proses');
        Route::post('/update/{id}', 'PengirimanController@update')->name('pengiriman.update');
        Route::get('/terima/{id}', 'PengirimanController@terima')->name('pengiriman.terima');
        Route::get('/request/{id}', 'PengirimanController@requestPengiriman')->name('pengiriman.request');
        Route::get('/cetak/{id}', 'PengirimanController@cetakSJ')->name('pengiriman.cetaksj');
    });

    Route::group(['prefix' => 'laporan'], function () {
        Route::get('/pesanan', 'LaporanController@pesanan')->name('laporan.pesanan');
        Route::post('/pesanan/cetak', 'LaporanController@pesananCetak')->name('laporan.pesanan.cetak');
        Route::get('/pengiriman', 'LaporanController@pengiriman')->name('laporan.pengiriman');
        Route::post('/pengiriman/cetak', 'LaporanController@pengirimanCetak')->name('laporan.pengiriman.cetak');
        Route::get('/pengadaan', 'LaporanController@pengadaan')->name('laporan.pengadaan');
        Route::post('/pengadaan/cetak', 'LaporanController@pengadaanCetak')->name('laporan.pengadaan.cetak');
    });


    Route::get('/', function() {
        return redirect()->route('index');
    });


});

app/Supplier.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    protected $table = 'supplier';

	public $timestamps = false;

	protected $primaryKey = 'kode_supplier';

	public $incrementing = false;
	
	public function user()
    {
    	return $this->belongsTo('App\User');
    }

}

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use App\{Supplier, User};
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Image;
use Exception, DB;

class SupplierController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $param = $request->filter;

        $suppliers = Supplier::join('users', 'users.id', '=', 'supplier.user_id')
                ->select('supplier.kode_supplier as id', 'users.nama', 'users.email', 'users.kontak', 'users.alamat')
                ->where('supplier.kode_supplier', 'like', '%' . ($request->filter['kode'] ?? '')  . '%')
                ->where('users.nama', 'like', '%' . ($request->filter['nama'] ?? '')  . '%')
                ->where('users.email', 'like', '%' . ($request->filter['email'] ?? '') . '%')
                ->where('users.kontak', 'like', '%' . ($request->filter['kontak'] ?? '') . '%')
                ->where('users.alamat', 'like', '%' . ($request->filter['alamat'] ?? '')  . '%')
                ->paginate(10);

        return view('supplier.index', compact('suppliers', 'param'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('supplier.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:50|alpha',
            'email' => 'email|unique:users,email',
            'password' => 'required|string|min:6',
            'kontak' => 'required|numeric',
            'foto'  => 'nullable|image',
            'alamat' => 'required|string|max:200',
        ]);

        $imgname = Null;
        if( !is_null($request->foto) ){
            $imageLocation = public_path('images/foto').'/';

            $imgname = 'supplier-'.time().'.'.$request->foto->getClientOriginalExtension();
            Image::make($request->foto)->resize(300, 300)
                    ->save($imageLocation .$imgname);
        }

        DB::beginTransaction();
        try {

            $user = new User;
            $user->nama = $request->name;
            $user->email = $request->email;
            $user->password = bcrypt($request->password);
            $user->jenis_kelamin = $request->jeniskelamin;
            $user->alamat = $request->alamat ?? '-';
            $user->kontak = $request->kontak ?? '-';
            $user->foto = $imgname;
            $user->save();

            $supplier = New Supplier;
            $supplier->user_id = $user->id;
            $supplier->kode_supplier = 'S_'.ucwords($request->name[0]).substr(ucwords($request->name), -1);
            $supplier->save();

            DB::commit();

        } catch (Exception $e) {

            DB::rollBack();
            return redirect()->back()->withInput()->with('alert-error', $e->getMessage());

        }

        return redirect()->route('supplier.index')->with('alert-success', 'Berhasil menambah supplier!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function show(Supplier $supplier)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $supplier = Supplier::findOrFail($id);
        return view('supplier.edit', compact('supplier'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $supplier = Supplier::findOrFail($id);

        $user = User::findOrFail($supplier->user_id);

        $this->validate($request, [
            'name' => 'required|min:4|max:50|alpha',
            'email' => [
                'required',
                'email',
                Rule::unique('users')->ignore($user->id),
            ],
            'password' => 'nullable|string|min:6',
            'kontak' => 'required|numeric',
            'foto'  => 'nullable|image',
            'alamat' => 'required|string|max:200'
        ]);

        DB::beginTransaction();
        try {

            $imgname = Null;

            if( !is_null($request->foto) ){
                $imageLocation = public_path('images/foto').'/';

                $img = $user->foto;
                !file_exists($imageLocation.$img) or unlink($imageLocation.$img);

                $imgname = 'supplier-'.time().'.'.$request->foto->getClientOriginalExtension();
                Image::make($request->foto)->resize(300, 300)
                        ->save($imageLocation .$imgname);
            }

            $supplier->save();

            $user->nama = $request->name;
            $user->email = $request->email;
            if(!is_null($request->password))
                $user->password = bcrypt($request->password);
            $user->jenis_kelamin = $request->jeniskelamin;
            $user->alamat = $request->alamat ?? '-';
            $user->kontak = $request->kontak ?? '-';
            $user->foto = $imgname;
            $user->save();

            DB::commit();

        } catch (Exception $e) {

            DB::rollBack();
            return redirect()->back()->withInput()->with('alert-error', $e->getMessage());

        }

        return redirect()->route('supplier.index')->with('alert-success', 'Berhasil mengubah supplier!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $supplier = Supplier::findOrFail($id);
        $user = User::findOrFail($supplier->user_id);

        $img = $user->foto;

        DB::beginTransaction();
        try {

            $supplier->delete();
            $user->delete();

            DB::commit();

        } catch (Exception $e) {

            DB::rollBack();
            return redirect()->back()->withInput()->with('alert-error', $e->getMessage());

        }

        $imageLocation = public_path('images/foto').'/';
        if (!is_null($img)) !file_exists($imageLocation.$img) or unlink($imageLocation.$img);

        return redirect()->back()->with('alert-success', 'Berhasil menghapus data supplier.');
    }
}

resources/views/supplier/create.blade.php
@extends('layouts.app')

@section('css')
<link rel="stylesheet" type="text/css" href="{{ asset('guru/default/assets/pages/j-pro/css/demo.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('guru/default/assets/pages/j-pro/css/font-awesome.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('guru/default/assets/pages/j-pro/css/j-pro-modern.css') }}">
@endsection

@section('content')
<div class="page-header card">
    <div class="row align-items-end">
        <div class="col-lg-8">
            <div class="page-header-title">
                <i class="icofont icofont-box bg-c-green"></i>
                <div class="d-inline">
                    <h4>Tambah Data Supplier</h4>
                    <span></span>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="page-header-breadcrumb">
                <ul class="breadcrumb-title">
                    <li class="breadcrumb-item">
                        <a href="{{ route('index') }}">
                            <i class="icofont icofont-home"></i>
                        </a>
                    </li>
                    <li class="breadcrumb-item"><a href="{{ route('supplier.index') }}">Supplier</a>
                    </li>
                    <li class="breadcrumb-item"><a href="#">Tambah Supplier</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="page-body">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-block">
                    <div class="j-wrapper j-wrapper-640">
                        <form action="{{ route('supplier.store') }}" method="post" class="j-pro" id="j-pro" novalidate="" enctype="multipart/form-data">
                            @csrf
                            <div class="j-content">
                                <!-- start name -->
                                <div class="j-unit">
                                    <label class="j-label">Nama Lengkap</label>
                                    <div class="j-input {{ $errors->has('name') ? ' j-error-view' : '' }}">
                                        <label class="j-icon-right" for="name">
                                            <i class="icofont icofont-ui-user"></i>
                                        </label>
                                        <input type="text" id="name" name="name" value="{{ old('name') }}">
                                        @if ( $errors->has('name') )
                                            <span class="j-error-view">{{$errors->first('name')}}</span>
                                        @endif
                                    </div>
                                </div>
                                <!-- end name -->

                                <!-- start email phone -->
                                <div class="j-row">
                                    <div class="j-span6 j-unit">
                                        <label class="j-label">Email</label>
                                        <div class="j-input {{ $errors->has('email') ? ' j-error-view' : '' }}">
                                            <label class="j-icon-right" for="email">
                                                <i class="icofont icofont-envelope"></i>
                                            </label>
                                            <input type="email" id="email" name="email" value="{{ old('email') }}">
                                        @if ( $errors->has('email') )
                                            <span class="j-error-view">{{$errors->first('email')}}</span>
                                        @endif
                                        </div>
                                    </div>
                                    <div class="j-span6 j-unit">
                                        <label class="j-label">Password</label>
                                        <div class="j-input {{ $errors->has('password') ? ' j-error-view' : '' }}"">
                                            <label class="j-icon-right" for="password">
                                                <i class="icofont icofont-key"></i>
                                            </label>
                                            <input type="password" id="password" name="password">
                                        @if ( $errors->has('password') )
                                            <span class="j-error-view">{{$errors->first('password')}}</span>
                                        @endif
                                        </div>
                                    </div>
                                </div>
                                <!-- start date -->
                                <div class="j-row">
                                    <div class="j-span6 j-unit">
                                        <label class="j-label">Jenis Kelamin</label>
                                        <div class="j-input">
                                            <label class="input select" id="show-elements-select">
                                                <select name="jeniskelamin">
                                                   <option value="Laki-Laki" {{ old('jeniskelamin') == 'Laki-Laki' ? 'selected' : ''}}>Laki-Laki</option>
                                                   <option value="Perempuan" {{ old('jeniskelamin') == 'Perempuan' ? 'selected' : ''}}>Perempupan</option>
                                                </select>
                                                <i></i>
                                            </label>
                                        </div>
                                    </div>
                                    <div class="j-span6 j-unit">
                                        <label class="j-label">Kontak</label>
                                        <div class="j-input {{ $errors->has('kontak') ? ' j-error-view' : '' }}"">
                                            <label class="j-icon-right" for="kontak">
                                                <i class="icofont icofont-phone"></i>
                                            </label>
                                            <input type="text" id="kontak" name="kontak" value="{{ old('kontak') }}">
                                        @if ( $errors->has('kontak') )
                                            <span class="j-error-view">{{$errors->first('kontak')}}</span>
                                        @endif
                                        </div>
                                    </div>
                                </div>
                                <div class="j-unit">
                                    <div class="j-input j-append-small-btn {{ $errors->has('foto') ? ' j-error-view' : '' }}">
                                        <div class="j-file-button">
                                            Browse
                                            <input type="file" id="file2" name="foto" onchange="document.getElementById('file2_input').value = this.value;">
                                        </div>
                                        <input type="text" id="file2_input" readonly="" placeholder="Upload Foto Supplier">
                                        <span class="j-hint">Ukuran foto 512x512px / 300x300px </span>
                                        @if ( $errors->has('foto') )
                                            <span class="j-error-view">{{$errors->first('foto')}}</span>
                                        @endif
                                    </div>
                                </div>
                                <!-- end date -->
                                <div class="j-divider j-gap-bottom-25"></div>
                                <!-- start message -->
                                <div class="j-unit">
                                    <label class="j-label">Alamat</label>
                                    <div class="j-input {{ $errors->has('alamat') ? ' j-error-view' : '' }}"">
                                        <textarea spellcheck="false" name="alamat">{{ old('alamat') }}</textarea>
                                        @if ( $errors->has('alamat') )
                                            <span class="j-error-view">{{$errors->first('alamat')}}</span>
                                        @endif
                                    </div>
                                </div>
                                <!-- end message -->
                                <!-- start response from server -->
                                <div class="j-response"></div>
                                <!-- end response from server -->
                            </div>
                            <!-- end /.content -->
                            <div class="j-footer">
                                <button type="submit" class="btn btn-primary">Simpan</button>
                            </div>
                            <!-- end /.footer -->
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<form action="" method="POST" id="deleteForm">
    @csrf
    @method('DELETE')
    <input type="submit" style="display: none;">
</form>
@endsection

@section('js')
<script type="text/javascript">
$('button#delete').on('click', function(){
    var href = $(this).attr('href');
    var title = $(this).data('title');
    swal({
      title: "Anda yakin akan menghapus supplier bernama "+ title +" ?",
      text: "Setelah dihapus data tidak dapat dikembalikan !",
      icon: "warning",
      buttons: true,
      dangerMode: true,
    })
    .then((willDelete) => {
      if (willDelete) {
        $('#deleteForm').attr('action', href);
        $('#deleteForm').submit();
      }
    });
});
</script>
@endsection

resources/views/supplier/index.blade.php
@extends('layouts.app')

@section('content')
<div class="page-header card">
    <div class="row align-items-end">
        <div class="col-lg-8">
            <div class="page-header-title">
                <i class="icofont icofont-box bg-c-green"></i>
                <div class="d-inline">
                    <h4>Kelola Data Supplier</h4>
                    <span>Tambah Data Supplier, Ubah Data Supplier dan Hapus Data Supplier</span>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="page-header-breadcrumb">
                <ul class="breadcrumb-title">
                    <li class="breadcrumb-item">
                        <a href="{{ route('index') }}">
                            <i class="icofont icofont-home"></i>
                        </a>
                    </li>
                    <li class="breadcrumb-item"><a href="{{ route('supplier.index') }}">Supplier</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="page-body">
    <div class="card">
        <div class="card-header">
            <a href="{{ route('supplier.create') }}"><button class="btn btn-sm btn-primary">Tambah Supplier</button></a>
        </div>
        <div class="card-block table-border-style">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Kode Supplier</th>
                            <th>Nama</th>
                            <th>Kontak</th>
                            <th>Email</th>
                            <th>Alamat</th>
                            <th>#</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr style="background:#e9ecef">
                            <form action="" method="GET" name="search_form" id="search_form">
                            <td>
                                <input type="text" class="form-control form-control-sm" name="filter[kode]" value="{{ $param['kode'] ?? '' }}">
                            </td>
                            <td>
                                <input type="text" class="form-control form-control-sm" name="filter[nama]" value="{{ $param['nama'] ?? '' }}">
                            </td>
                            <td>
                                <input type="text" class="form-control form-control-sm" name="filter[kontak]" value="{{ $param['kontak'] ?? ''}}">
                            </td>
                            <td>
                                <input type="text" class="form-control form-control-sm" name="filter[email]" value="{{ $param['email'] ?? ''}}">
                            </td>
                            <td>
                                <input type="text" class="form-control form-control-sm" name="filter[alamat]" value="{{ $param['alamat'] ?? ''}}">
                            </td>
                            <td>
                                <button type="submit" class="btn btn-info btn-bordered btn-sm">Cari
                                </button>
                                <button type="reset" onclick="javascript:window.location.assign('{{ route('supplier.index') }}');" class="btn btn-info btn-bordered btn-sm">
                                    Reset
                                </button>
                            </td>
                            </form>
                        </tr>
                    @foreach ($suppliers as $supplier)
                        <tr>
                            <td>{{ $supplier->id }}</td>
                            <td>{{ $supplier->nama }}</td>
                            <td>{{ $supplier->kontak }}</td>
                            <td>{{ $supplier->email }}</td>
                            <td>{{ $supplier->alamat }}</td>
                            <td>
                                <a href="{{ route('supplier.edit', $supplier->id) }}">
                                    <button class="btn btn-mini btn-warning">Edit</button>
                                </a>
                                <button id="delete" data-title="{{$supplier->nama}}" href="{{ route('supplier.destroy', $supplier->id) }}" class="btn btn-mini btn-danger">Hapus</button>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <div style="padding: 15px;width: 100%">
                    <center>{{ $suppliers->appends(request()->except('page'))->links() }}</center>
                </div>
            </div>
        </div>
    </div>
</div>

<form action="" method="POST" id="deleteForm">
    @csrf
    @method('DELETE')
    <input type="submit" style="display: none;">
</form>
@endsection

@section('js')
<script type="text/javascript">
$('button#delete').on('click', function(){
    var href = $(this).attr('href');
    var title = $(this).data('title');
    swal({
      title: "Anda yakin akan menghapus supplier bernama "+ title +" ?",
      text: "Setelah dihapus data tidak dapat dikembalikan !",
      icon: "warning",
      buttons: true,
      dangerMode: true,
    })
    .then((willDelete) => {
      if (willDelete) {
        $('#deleteForm').attr('action', href);
        $('#deleteForm').submit();
      }
    });
});
</script>
@endsection